version: '2'
services:
    data_server_1:
        image: pythonado
        volumes:
            - "../..:/web_gui:rw"
        entrypoint: "/web_gui/buggy_data_server.py"

    http_server_1:
        image: pythonado
        volumes:
            - "../..:/web_gui:ro"
        entrypoint: "/web_gui/buggy_http_server.py"
        links:
            - data_server_1 

    http_server_2:
        image: pythonado
        volumes:
            - "../..:/web_gui:ro"
        entrypoint: "/web_gui/buggy_http_server.py"
        links:
            - data_server_1 

    nginx:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
            - "4242:4242"
        links:
            - data_server_1 
            - http_server_1 
            - http_server_2
        volumes:
            - "../../nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "../../static:/www/static"
            - "../../protos:/www/protos"
