version: '2'
services:
    server1:
        build: .
        ports: 
            - "80"
        volumes:
            - "..:/buggy:ro"
        entrypoint: "/buggy/buggy_http_server.py"

    server2:
        build: .
        ports:
            - "80"
        volumes:
            - "..:/buggy:ro"
        entrypoint: "/buggy/buggy_http_server.py"

    nginx:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - server1
            - server2
        volumes:
            - "../nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "../static:/www/static"
            - "../protos:/www/protos"
